version: "3.1"
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nizer
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
